### ISSUE TITLE
tz_offset_ not working on sunrise

### ISSUE THREAD

**Issue by KammutierSpule** [adonmo/daylight#1]
I tested the tz_offset_ parameter, but changing it, doesn't make any change on output.

**Comment by chaitan94** [comment]
Hi Mario, could  you provide a bit more context, what are the inputs you are trying, what is the seen output and what is the expected output?

It's been quite long time since I worked on this project, but I think timezone is just representational. It is just for being able to make the output more readable. It doesn't actually change the sunrise time in an absolute sense. The main factor is instead the location given by latitude and longitude. I hope that might possibly answer your question, if I understand you correctly.

**Comment by KammutierSpule** [comment]
Sunclock::Sunclock(double const &latitude_, double const &longitude_, double const &tz_offset_)

I mean, using tz_offset_, there is no effect on 
time_t Sunclock::sunrise(time_t date) {

if that is UTC+0 it will be ok all the time.

**Comment by chaitan94** [comment]
I don't remember it clearly, but if I am not wrong, both input and ouput of sunrise are in UTC.

tz_offset only comes into picture when deciding the date at given location. Here's how I remember it works:

1. We take input in UTC
2. We use tz_offset to know the date and time at the interested location (note: date can change here compared to UTC)
3. We calculate sunrise time for that date and location
4. We convert  sunrise time back to UTC (again, using tz_offset) and return it
